<h1 style="display:inline-block">ActiveVoxel Design</h1><br/>

subdivide( get_faces( solid ), divisions )

In [ ]:
# cube_vxs = [[ px py pz t id demi? ] ...]

# t is the level of division of the unitary space
# p is a multiplier <= t

In [1]:
import numpy as np

vxs_py = [[ 1, 0, 0, 1, 0, 0 ], [ 0, 0, 0, 1, 1, 0 ], [ 0, 0, 1, 1, 2, 0 ], [ 1, 0, 1, 1, 3, 0 ], 
          [ 0, 1, 1, 1, 4, 0 ], [ 1, 1, 1, 1, 5, 0 ], [ 0, 1, 0, 1, 6, 0 ], [ 1, 1, 0, 1, 7, 0 ]]

vxs = np.array( vxs_py )

print( vxs.transpose() )


[[1 0 0 1 0 1 0 1]
 [0 0 0 0 1 1 1 1]
 [0 0 1 1 1 1 0 0]
 [1 1 1 1 1 1 1 1]
 [0 1 2 3 4 5 6 7]
 [0 0 0 0 0 0 0 0]]


In [3]:
tmax = 1

vx_names = { ( tmax + 1 ) * ( tmax + 1 ) * vx[ 0 ] + ( tmax + 1 ) * vx[ 1 ] + vx[ 2 ]: 
             ( vx[ 3 ], vx[ 0 ], vx[ 1 ], vx[ 2 ], tmax ) for vx in vxs_py }

print( vx_names )


{4: (0, 1, 0, 0, 1), 0: (1, 0, 0, 0, 1), 1: (2, 0, 0, 1, 1), 5: (3, 1, 0, 1, 1), 3: (4, 0, 1, 1, 1), 7: (5, 1, 1, 1, 1), 2: (6, 0, 1, 0, 1), 6: (7, 1, 1, 0, 1)}


In [4]:
# vx1 vx2 id parent

edges_meta_py = [[ 0, 1, 1, 1 ], [ 1, 2, 2, 2 ], [ 2, 3, 3, 3 ], [ 3, 0, 4, 4 ], [ 2, 4, 5, 5 ], 
                 [ 4, 5, 6, 6 ], [ 5, 3, 7, 7 ], [ 4, 6, 8, 8 ], [ 6, 7, 9, 9 ], [ 7, 5, 10, 10 ],
                 [ 6, 1, 11, 11 ], [ 0, 7, 12, 12 ]]

edges_meta = np.array( edges_meta_py )

print( edges_meta.transpose())


[[ 0  1  2  3  2  4  5  4  6  7  6  0]
 [ 1  2  3  0  4  5  3  6  7  5  1  7]
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
 [ 1  2  3  4  5  6  7  8  9 10 11 12]]


In [13]:
# dx dy dz
# direction vector = vx2 - vx1

edt_py = [[ vxs_py[ id[ 0 ]][ 0 ], 
            vxs_py[ id[ 0 ]][ 1 ], 
            vxs_py[ id[ 0 ]][ 2 ]] 
              for id in edges_meta_py ]

edges_data = np.array( edt_py )

edt_py2 = [[ vxs_py[ id[ 1 ]][ 0 ], 
            vxs_py[ id[ 1 ]][ 1 ], 
            vxs_py[ id[ 1 ]][ 2 ]] 
              for id in edges_meta_py ]

ed2 = np.array( edt_py2 )

edges_data -= ed2

print( edges_data.transpose())


[[ 1  0 -1  0  0 -1  0  0 -1  0  0  0]
 [ 0  0  0  0 -1  0  1  0  0  0  1 -1]
 [ 0 -1  0  1  0  0  0  1  0 -1  0  0]]


In [24]:
# edge1 edge2 id
# id < 0 = reversed edge

tris_py = [[  1,  2, 0 ], [  3,  4, 1 ], [  -3,  5, 2 ], [  6,   7, 3 ], [  -6,  8,  4 ], [  9, 10,  5 ],
           [ -9, 11, 6 ], [ -1, 12, 7 ], [ -12, -4, 8 ], [ -7, -10, 9 ], [ -11, -8, 10 ], [ -5, -2, 11 ]]

tris = np.array( tris_py )

print( tris.transpose())


[[  1   3  -3   6  -6   9  -9  -1 -12  -7 -11  -5]
 [  2   4   5   7   8  10  11  12  -4 -10  -8  -2]
 [  0   1   2   3   4   5   6   7   8   9  10  11]]


In [25]:
faces_py = [[ 0, 1, 0 ], [ 2, 3, 1 ], [ 4, 5, 2 ], [ 6, 7, 3 ], [ 8, 9, 4 ], [ 10, 11, 5 ]]

faces = np.array( faces_py )

print( faces.transpose())


[[ 0  2  4  6  8 10]
 [ 1  3  5  7  9 11]
 [ 0  1  2  3  4  5]]


In [26]:
def subdivide( _faces, divs ):
    _tris = [[ tris[ tri ][ 0 ], tris[ tri ][ 1 ]]  for tri in _faces ]
    _tris = [ item for sublist in _tris for item in sublist ]
    print( _tris )

subdivide( faces[ 0 ][ 0:1 ], 3 )


[1, 2]
