<h1 style="display:inline-block">ActiveVoxel Design</h1><br/>

subdivide( get_faces( solid ), divisions )

In [ ]:
# cube_vxs = [[ px py pz id demi? ] ...]
            

In [12]:
import numpy as np

vxs_py = [[ 1, 0, 0, 0, 0 ], [ 0, 0, 0, 1, 0 ], [ 0, 0, 1, 2, 0 ], [ 1, 0, 1, 3, 0 ], [ 0, 1, 1, 4, 0 ], [ 1, 1, 1, 5, 0 ], 
       [ 0, 1, 0, 6, 0 ], [ 1, 1, 0, 7, 0 ]]

vxs = np.array( vxs_py )

print( vxs.transpose() )


[[1 0 0 1 0 1 0 1]
 [0 0 0 0 1 1 1 1]
 [0 0 1 1 1 1 0 0]
 [0 1 2 3 4 5 6 7]
 [0 0 0 0 0 0 0 0]]


In [3]:
tmax = 1

vx_names = { ( tmax + 1 ) * ( tmax + 1 ) * vx[ 0 ] + ( tmax + 1 ) * vx[ 1 ] + vx[ 2 ]: 
             ( vx[ 3 ], vx[ 0 ], vx[ 1 ], vx[ 2 ], tmax ) for vx in vxs_py }

print( vx_names )


{4: (0, 1, 0, 0, 1), 0: (1, 0, 0, 0, 1), 1: (2, 0, 0, 1, 1), 5: (3, 1, 0, 1, 1), 3: (4, 0, 1, 1, 1), 7: (5, 1, 1, 1, 1), 2: (6, 0, 1, 0, 1), 6: (7, 1, 1, 0, 1)}


In [11]:
# vx1 vx2 id parent

edges_meta_py = [[ 0, 1, 1, 1 ], [ 1, 2, 2, 2 ], [ 2, 3, 3, 3 ], [ 3, 0, 4, 4 ], [ 2, 4, 5, 5 ], 
                 [ 4, 5, 6, 6 ], [ 5, 3, 7, 7 ], [ 4, 6, 8, 8 ], [ 6, 7, 9, 9 ], [ 7, 5, 10, 10 ],
                 [ 6, 1, 11, 11 ], [ 0, 7, 12, 12 ]]

edges_meta = np.array( edges_meta_py )

print( edges_meta.transpose())


[[ 0  1  2  3  2  4  5  4  6  7  6  0]
 [ 1  2  3  0  4  5  3  6  7  5  1  7]
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
 [ 1  2  3  4  5  6  7  8  9 10 11 12]]


In [10]:
# dx dy dz t pos